title: Satoe Sakuma
description: Engineer, health policy student, and soon Engineering Manager on Health AI at Whoop. Personal site of Satoe Sakuma.
url: https://satoesakuma.com
markdown: kramdown
email: satoesakuma@gmail.com

permalink: /tech-blog/:year/:month/:day/:title

collections:
  reflections:
    output: false